server:
  port: '8085'
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/dinermore
    password: Renuka*123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: 'false'
logging:
  level:
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG